name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Replace Firebase Configuration
        run: |
          sed -i 's/process.env.API_KEY_PLACEHOLDER/${{ secrets.FIREBASE_API_KEY }}/' ./script.js
          sed -i 's/process.env.APP_ID_PLACEHOLDER/${{ secrets.FIREBASE_APP_ID }}/' ./script.js
          sed -i 's/process.env.AUTH_DOMAIN_PLACEHOLDER/${{ secrets.FIREBASE_AUTH_DOMAIN }}/' ./script.js
          sed -i 's/process.env.DATABASE_URL_PLACEHOLDER/${{ secrets.FIREBASE_DATABASE_URL }}/' ./script.js
          sed -i 's/process.env.MEASUREMENT_ID_PLACEHOLDER/${{ secrets.FIREBASE_MEASUREMENT_ID }}/' ./script.js
          sed -i 's/process.env.MESSAGING_SENDER_ID_PLACEHOLDER/${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}/' ./script.js
          sed -i 's/process.env.PROJECT_ID_PLACEHOLDER/${{ secrets.FIREBASE_PROJECT_ID }}/' ./script.js
          sed -i 's/process.env.STORAGE_BUCKET_PLACEHOLDER/${{ secrets.FIREBASE_STORAGE_BUCKET }}/' ./script.js

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
